# Generated by Django 5.1.2 on 2024-10-16 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='Books',
        ),
    ]
