# Generated by Django 5.1.1 on 2024-10-30 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_rename_employee_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='picture',
            field=models.ImageField(null=True, upload_to='book_images'),
        ),
    ]
