# Generated by Django 5.1.2 on 2024-10-17 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='qualification',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
