# Generated by Django 5.1.2 on 2024-10-17 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_employee_qualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='mobile',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
